friend_score_twitter:
    resource: "@FriendScoreTwitterBundle/Controller/"
    type:     annotation
    prefix:   /twitter

friend_score_facebook:
    resource: "@FriendScoreFacebookBundle/Controller/"
    type:     annotation
    prefix:   /facebook

